services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: socialmetrics_db
    ports:
      - "3306:3306"

  api:
    # build: .
    image: lowinne/socialmetrics-api:latest
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: socialmetrics_db
    depends_on:
      - db